name: GitHub Actions for PsPM
on: [push]
jobs:
  PsPM-test:
    runs-on: ubuntu-latest
    steps:
      
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Checkout private tools
        uses: actions/checkout@v2
        with:
          repository: PsPM-data-priv
          token: ${{ github.token }}
          #'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' # `GH_PAT` is a secret that contains your PAT
          path: ImportTestData