name: GitHub Actions for PsPM
on: [push]
jobs:
  PsPM-test:
    runs-on: ubuntu-latest
    steps:
      
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Checkout private tools
        uses: actions/checkout@v2
        with:
          repository: teddychao/PsPM-data-priv
          token: ${{ secrets.MY_REPO_PAT }}
          path: ImportTestData